### ISSUE TITLE
Issue after model averaging

### ISSUE THREAD

**Issue by dimitarsh1** [lovecambi/qebrain#1]
Dear Kai, 

I am getting the following error during training the expert model.

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

tensor_name = skil_count; expected dtype int32 does not equal original dtype float
         [[node save/RestoreV2 (defined at expert_model.py:726)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
         [[{{node save/RestoreV2/_261}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_171_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Any idea what's going on and how to fix it?

Thanks,
Dimitar

**Comment by dimitarsh1** [comment]
By the way, I am running only on one GPU as the other is busy with other experiments all the time.

I have the 1.12 version of tensorflow-gpu. Running on Titan X.

Thanks.
Dimitar

**Comment by lovecambi** [comment]
Can you pull the recent updated version? I think it should be fixed.

**Comment by dimitarsh1** [comment]
Thanks, that works now.

I guess you may close the issue.

Cheers
