### ISSUE TITLE
Does this version of code include "Boosting Model Performance" in the paper?

### ISSUE THREAD

**Issue by meettyj** [lovecambi/qebrain#12]
In the paper, you mentioned Human-crafted Features, Artificial QE Data Construction and Greedy Ensemble Selection have been used to improve performance. However, I couldn't find any related part in your code. Am I wrong or you just ignore implementing it in this version of code? Thanks!

**Comment by lovecambi** [comment]
In the data folder, I have included some tfrecord data, which is an example of hand crafted feature.

Average ensemble also works well. You can simply try it.

**Comment by meettyj** [comment]
Thanks.
