### ISSUE TITLE
tf.concat?

### ISSUE THREAD

**Issue by zaiheshi** [lovecambi/qebrain#13]
Hello！ 
I am sorry! I have a question,  in line 1294 of qe_model.py, why using tf.concat instead of shift_concat  or shift_outputs ?

**Comment by lovecambi** [comment]
It is the forward and backward information including the current token.

**Comment by zaiheshi** [comment]
Thanks!  pre_qefv is the model derived feature(z, e) mentioned in the paper.  is post_qefv mentioned also?

**Comment by genbei** [comment]
> Thanks! pre_qefv is the model derived feature(z, e) mentioned in the paper. is post_qefv mentioned also?

so  is post_qefv mentioned also?you see？
