### ISSUE TITLE
STEP 2: Preprocessing including tokenization, lowercasing, and vocabulary files.

### ISSUE THREAD

**Issue by Ostyk** [lovecambi/qebrain#17]
Hi, I was wondering if you could please guide me in the 2nd step of the README file. 
My goal is to use your network to predict the post-editing effort on MT output. 

I have my own corpus from a CAT tool, having the source, MT output, and target from translators. I am using https://github.com/VKCOM/YouTokenToMe for BPE tokenization, but I am not sure how to split my data and how to tokenize it.
I split my data into train, val, test for each of the above mentioned(source, MT, target) parallel data. 
My question is how should I feed the data into the expert_model.py file? Should it be tokenized using BPE already? also in txt format? 

Thanks in advance,
Michal

**Comment by lovecambi** [comment]
You can use plain test file for each language, where each line is a tokenized sentence.

If you are using BPE tokens, sentence level training is OK. 

But for word level prediction, there is a discrepancy between word labels and BPE tokens. So you need to modify the code or the data. (1) The easier way is to modify the data. For each BPE token, you assign the same label as the word it comes from. (2) You can also modify the code by following the sequence labeling rule in BERT fine-tuning -- only predict the first BPE token of each word.
