### ISSUE TITLE
How to make word-level prediction

### ISSUE THREAD

**Issue by genbei** [lovecambi/qebrain#21]
I want to make word-level prediction, and set it in the `--train_level=word`
The following cuowu was encountered

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 1000

How to solve it, please. Thank you very much

**Comment by lovecambi** [comment]
How did you prepare the dataset?

**Comment by genbei** [comment]
> How did you prepare the dataset?

The data set is not processed, but only labeled with source. 1 means ok, and 0 means bad. Is there anything to pay attention to or deal with, please

**Comment by lovecambi** [comment]
> > How did you prepare the dataset?
> 
> The data set is not processed, but only labeled with source. 1 means ok, and 0 means bad. Is there anything to pay attention to or deal with, please

Can you post the whole error msg?

**Comment by genbei** [comment]
> > > How did you prepare the dataset?
> > 
> > 
> > The data set is not processed, but only labeled with source. 1 means ok, and 0 means bad. Is there anything to pay attention to or deal with, please
> 
> Can you post the whole error msg?

`# External evaluation, global step 0
  done, num sentences 1000, time 22s
qe_model.py:1424: UserWarning: loadtxt: Empty input file: "./saved_qe_model_enzh_word/output_dev.sent"
  pre = np.loadtxt(pre_file)
Traceback (most recent call last):
  File "qe_model.py", line 2190, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/lyn19/miniconda3/envs/tf1.12/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "qe_model.py", line 2183, in main
    run_main(FLAGS, default_hparams, train, inference)
  File "qe_model.py", line 2178, in run_main
    train_fn(hparams, target_session=target_session)
  File "qe_model.py", line 1738, in train
    run_external_eval(infer_model, infer_sess, model_dir, hparams, summary_writer)
  File "qe_model.py", line 1589, in run_external_eval
    avg_ckpts=avg_ckpts)
  File "qe_model.py", line 1534, in _external_eval
    metrics=hparams.metrics)
  File "qe_model.py", line 1510, in decode_and_evaluate
    score = evaluate(ref_file, pred_file, metric)
  File "qe_model.py", line 1411, in evaluate
    evaluation_score = _pearson(ref_file + sent_suffix, pred_file + ".sent")
  File "qe_model.py", line 1426, in _pearson
    return np.corrcoef(pre, grt)[0, 1]
  File "<__array_function__ internals>", line 6, in corrcoef
  File "/home/lyn19/miniconda3/envs/tf1.12/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2551, in corrcoef
    c = cov(x, y, rowvar)
  File "<__array_function__ internals>", line 6, in cov
  File "/home/lyn19/miniconda3/envs/tf1.12/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2415, in cov
    X = np.concatenate((X, y), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 1000
`

**Comment by genbei** [comment]
> > > How did you prepare the dataset?
> > 
> > 
> > The data set is not processed, but only labeled with source. 1 means ok, and 0 means bad. Is there anything to pay attention to or deal with, please
> 
> Can you post the whole error msg?

this is my qe_train.sh
`python qe_model.py \
      --src=en \
      --mt=zh\
      --fea=word.tfrecord \
      --lab=wtag \
      --train_prefix=${datadir}/train \
      --dev_prefix=${datadir}/dev \
      --test_prefix=${datadir}/dev \
      --vocab_prefix=${vocabdir}/vocab \
      --max_vocab_size=120000 \
      --out_dir=${modeldir} \
      --optimizer=lazyadam \
      --warmup_steps=8000 \
      --learning_rate=2.0 \
      --num_train_steps=75000 \
      --steps_per_stats=100 \
      --steps_per_external_eval=1000 \
      --rnn_units=128 \
      --rnn_layers=1 \
      --embedding_size=512 \
      --num_units=512 \
      --num_layers=2 \
      --ffn_inner_dim=512 \
      --qe_batch_size=64 \
      --infer_batch_size=64 \
      --metrics=pearson \
      --use_hf=False \
      --num_buckets=4 \
      --dim_hf=17 \
      --train_level=word \
      --avg_ckpts=True \
      --fixed_exp=True \
      --label_smoothing=0.1 \
      --exp_model_dir=${exp_modeldir}
`

**Comment by genbei** [comment]
> > > How did you prepare the dataset?
> > 
> > 
> > The data set is not processed, but only labeled with source. 1 means ok, and 0 means bad. Is there anything to pay attention to or deal with, please
> 
> Can you post the whole error msg?

I see. Thank you. I didn't specify  --metrics
