### ISSUE TITLE
Data type error when trained with cpu only

### ISSUE THREAD

**Issue by hittle2015** [lovecambi/qebrain#5]
on my mac, I set the num_gpus=0 and started training the expert model with the exp_train.sh script, which gives me the following error:
'''
TypeError: Value passed to parameter 'size_splits' has DataType float32 not in list of allowed values: int32, int64
'''
While I attempted to set the line in expert-model.py at line 549  as
'''
size_splits = [tf.floordiv(int(size + i), int(num_splits)) for i in range(num_splits)]------>size_splits = [tf.div(int(size + i), int(num_splits)) for i in range(num_splits)]
'''
It still does not work.

**Comment by lovecambi** [comment]
I didn't consider cpu training for expert model.  A workaround is to add in
https://github.com/lovecambi/qebrain/blob/771519de047279ea25d76b056ed64b78da6cc7c3/expert_model.py#L633
```
if len(self.devices) == 0:
    self.devices = ["/cpu:0"]
    setattr(hparams, "num_gpus", 1)
```

**Comment by hittle2015** [comment]
Thanks, and comment the assertion at line 632 as well?

**Comment by lovecambi** [comment]
I assume you set hparams.num_gpus = 0 by argparser.

**Comment by hittle2015** [comment]
Thanks. I really appreciate your help. Another question, I have successfully installed the tensorflow-gpu and other requirements on a gpu cluster. When I use the command 'nvidia-smi',I could see all six gpus, but the code still report assertion error. I checked with the command
"device_lib.list_local_devices()", I could only see cpu, no gpus are detected.
Any idea?

**Comment by hittle2015** [comment]
> I assume you set hparams.num_gpus = 0 by argparser.

either way, still have to comment line 632, as when I set num_gpus=0 at the end of exp_train.sh, assertion still complains.

**Comment by lovecambi** [comment]
> Thanks. I really appreciate your help. Another question, I have successfully installed the tensorflow-gpu and other requirements on a gpu cluster. When I use the command 'nvidia-smi',I could see all six gpus, but the code still report assertion error. I checked with the command
> "device_lib.list_local_devices()", I could only see cpu, no gpus are detected.
> Any idea? Did you test on a GPU cluster or workstation with multiple gpus? It looks like that Tensorflow could not pick up GPUs in my case.

Yes, I can run the expert model with 1 ~ 8 GPUs. If the tensorflow cannot see your GPUs, I guess you should carefully follow the official Tensorflow installation to make sure you install the tensorflow-gpu correctly .
